### ISSUE TITLE
Slash commands from botfather

### ISSUE THREAD

**Issue by Fedcomp** [lukefx/hubot-telegram#25]
Let's say i added command /hello to my bot. Now i try to catch it and i cant find how. Apparently bot threat /hello and hello the same.
Bot should treat registered slash commands as a mention + message. I dont want hello (without slash) to be processed at all (as common words may interfere with commands) but /hello should work like i mentioned the bot.

Is there a way to achieve that? so say i can make robot.respond /\/hello/i and it will work?

**Comment by arcturial** [comment]
The bot will treat /hello and hello the same only when you are having a one on one chat with the bot. If you are in a group chat (with privacy mode enabled), the bot will not respond to "hello" and will wait until it receives a message like "@bot hello" or "/hello". It has been implemented this way so that the behaviour is similar between different hubot adapters. 

The script you write shouldn't listen for `/\/hello/i` and instead should listen for `/hello/i`. The `getUpdates` command will only return commands that were meant for the bot (ie. all messages in private chat...only mentions of slash commands in group chat).

If you have privacy mode disabled in a group chat, all messages will be treated as potential bot commands and this can in turn cause a problem with common words. I would suggest making sure privacy mode is turned on, it will also make sure your bot does less processing.

**Comment by Fedcomp** [comment]
Thanks for response.
I am depend on bot.hear functionality, so i had to turn privacy mode off. Well, i guess turning it back on will solve my issues. Is there anyway could be possibility to process slash messages with bot.respond while privacy mode turned off? maybe environment variable? honestly i dont know how hard that would be to implement.

**Comment by arcturial** [comment]
Hey

Please try branch: https://github.com/lukefx/hubot-telegram/tree/issue-25

You can include it in your `package.json` file like `hubot-telegram: lukefx/hubot-telegram#issue-25`. This branch contains an environment variable called TELEGRAM_PRIVACY which will be 1 by default. If you make this variable 0, your messages will be processed without stripping out any slashes. 

Please beware that this will affect all chats. If you turn this feature off...it will forward the messages directly to the handlers, the only modification to them will be to make sure the robot name is added to messages originating from a private chat. 

I would suggest you rather use `robot.respond` for the specific slash commands you need instead of relying on `hear`. Doing so should eliminate accidental triggers since a user would have to mention the robot or add a `/` in front. 

Example (group chat):

`robot.respond(/hello/)`
- will trigger for `/hello`
- will trigger for `@bot hello`
- will trigger for `@botAlias hello`
- won't trigger for `hello`

Example (private chat):

`robot.respond(/hello/)`
- will trigger for `hello`
- will trigger for `@bot hello`
- will trigger for `/hello` (if you turn off TELEGRAM_PRIVACY, this will no longer trigger as the message will be evaluated WITH the forward slash and will only trigger for `robot.respond(/\/hello/i)`)

Please let me know if this will work for you and if you can provide some more detail on your use case I would appreciate it...I am still not sure why you would need to make the adapter aware of privacy mode.

**Comment by arcturial** [comment]
You should now be able to support this with the pull request https://github.com/lukefx/hubot-telegram/pull/34

You can add the bot alias "/" and the bot will respond to commands in a group chat like "/hello"

**Comment by Fedcomp** [comment]
hello, sorry for delay, had no time to test it, but thank you for your great work! glad it's merged into master now.
